// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package dht is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package dht

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Action int32

const (
	Message_REGISTER   Message_Action = 100
	Message_UNREGISTER Message_Action = 101
	Message_GET        Message_Action = 102
	Message_SET        Message_Action = 103
	Message_DELETE     Message_Action = 104
	Message_NOOP       Message_Action = 105
	Message_GET_ALL    Message_Action = 106
	Message_EXIT       Message_Action = 107
)

var Message_Action_name = map[int32]string{
	100: "REGISTER",
	101: "UNREGISTER",
	102: "GET",
	103: "SET",
	104: "DELETE",
	105: "NOOP",
	106: "GET_ALL",
	107: "EXIT",
}
var Message_Action_value = map[string]int32{
	"REGISTER":   100,
	"UNREGISTER": 101,
	"GET":        102,
	"SET":        103,
	"DELETE":     104,
	"NOOP":       105,
	"GET_ALL":    106,
	"EXIT":       107,
}

func (x Message_Action) Enum() *Message_Action {
	p := new(Message_Action)
	*p = x
	return p
}
func (x Message_Action) String() string {
	return proto.EnumName(Message_Action_name, int32(x))
}
func (x *Message_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Action_value, data, "Message_Action")
	if err != nil {
		return err
	}
	*x = Message_Action(value)
	return nil
}
func (Message_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message struct {
	Action           *Message_Action `protobuf:"varint,1,req,name=action,enum=dht.Message_Action" json:"action,omitempty"`
	Id               []byte          `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Key              *string         `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value            *string         `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	Success          *bool           `protobuf:"varint,5,opt,name=success" json:"success,omitempty"`
	Host             *string         `protobuf:"bytes,6,opt,name=host" json:"host,omitempty"`
	Keys             []string        `protobuf:"bytes,7,rep,name=keys" json:"keys,omitempty"`
	Values           []string        `protobuf:"bytes,8,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetAction() Message_Action {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return Message_REGISTER
}

func (m *Message) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Message) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Message) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *Message) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *Message) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *Message) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Message) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "dht.Message")
	proto.RegisterEnum("dht.Message_Action", Message_Action_name, Message_Action_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x8e, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x36, 0xdd, 0x8d, 0x63, 0x5a, 0x97, 0xf1, 0x32, 0xc7, 0x50, 0x2f, 0x3d, 0xe5,
	0xe0, 0x1b, 0x14, 0x5c, 0x4a, 0x21, 0xb6, 0xd2, 0x46, 0xf0, 0x26, 0x21, 0x59, 0x9b, 0x58, 0x35,
	0xe2, 0xa6, 0x82, 0xaf, 0xee, 0xc9, 0xc9, 0x1a, 0x7a, 0x9b, 0xdf, 0xf7, 0x87, 0xf9, 0x60, 0xfa,
	0x6e, 0x9d, 0x2b, 0x0f, 0x36, 0xfb, 0xfc, 0xea, 0xfa, 0x0e, 0x45, 0xdd, 0xf4, 0xf3, 0xdf, 0x00,
	0xd4, 0xfd, 0xbf, 0x8c, 0x37, 0x20, 0xcb, 0xaa, 0x6f, 0xbb, 0x0f, 0x0a, 0xd2, 0x70, 0x31, 0xbb,
	0xbd, 0xce, 0x38, 0x91, 0x8d, 0x6e, 0xb6, 0xf4, 0x16, 0x02, 0x84, 0x6d, 0x4d, 0x61, 0x1a, 0x2c,
	0x12, 0xbc, 0x04, 0x71, 0xb4, 0x3f, 0x24, 0x18, 0x2e, 0x70, 0x0a, 0x93, 0xef, 0xf2, 0xed, 0x64,
	0x29, 0xf2, 0x78, 0x05, 0xca, 0x9d, 0xaa, 0x8a, 0xcb, 0x34, 0x61, 0x21, 0xc6, 0x04, 0xa2, 0xa6,
	0x73, 0x3d, 0x49, 0x6f, 0x33, 0x71, 0xd5, 0x91, 0x4a, 0x05, 0xd3, 0x0c, 0xa4, 0xef, 0x3a, 0x8a,
	0x07, 0x9e, 0x5b, 0x90, 0xe3, 0xbb, 0x04, 0xe2, 0x9d, 0x59, 0xad, 0xf7, 0x85, 0xd9, 0xe9, 0x9a,
	0x73, 0xf0, 0xb8, 0x39, 0xb3, 0x45, 0x05, 0x62, 0x65, 0x0a, 0xfd, 0x32, 0x1c, 0x7b, 0x3e, 0x0e,
	0x3c, 0x4f, 0xde, 0x99, 0xdc, 0x14, 0x46, 0x37, 0x18, 0x43, 0xb4, 0xd9, 0x6e, 0x1f, 0x74, 0xcb,
	0x43, 0x15, 0xe7, 0x9e, 0x97, 0x79, 0xae, 0x5f, 0x07, 0xd9, 0x3c, 0xad, 0x0b, 0x7d, 0xfc, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x77, 0xbc, 0x28, 0x32, 0x11, 0x01, 0x00, 0x00,
}
