// Code generated by protoc-gen-go.
// source: request.proto
// DO NOT EDIT!

/*
Package mypackage is a generated protocol buffer package.

It is generated from these files:
	request.proto
	response.proto

It has these top-level messages:
	Request
	SetRequest
	GetRequest
	DeleteRequest
	RegisterRequest
	UnregisterRequest
	Response
	GetResponse
*/
package mypackage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Type int32

const (
	Request_SET        Request_Type = 1
	Request_GET        Request_Type = 2
	Request_DELETE     Request_Type = 3
	Request_REGISTER   Request_Type = 4
	Request_UNREGISTER Request_Type = 5
)

var Request_Type_name = map[int32]string{
	1: "SET",
	2: "GET",
	3: "DELETE",
	4: "REGISTER",
	5: "UNREGISTER",
}
var Request_Type_value = map[string]int32{
	"SET":        1,
	"GET":        2,
	"DELETE":     3,
	"REGISTER":   4,
	"UNREGISTER": 5,
}

func (x Request_Type) Enum() *Request_Type {
	p := new(Request_Type)
	*p = x
	return p
}
func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}
func (x *Request_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Request_Type_value, data, "Request_Type")
	if err != nil {
		return err
	}
	*x = Request_Type(value)
	return nil
}
func (Request_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Request struct {
	Type             *Request_Type      `protobuf:"varint,1,req,name=type,enum=dht.Request_Type" json:"type,omitempty"`
	Set              *SetRequest        `protobuf:"bytes,2,opt,name=set" json:"set,omitempty"`
	Get              *GetRequest        `protobuf:"bytes,3,opt,name=get" json:"get,omitempty"`
	Delete           *DeleteRequest     `protobuf:"bytes,4,opt,name=delete" json:"delete,omitempty"`
	Register         *RegisterRequest   `protobuf:"bytes,5,opt,name=register" json:"register,omitempty"`
	Unregister       *UnregisterRequest `protobuf:"bytes,6,opt,name=unregister" json:"unregister,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetType() Request_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Request_SET
}

func (m *Request) GetSet() *SetRequest {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *Request) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *Request) GetRegister() *RegisterRequest {
	if m != nil {
		return m.Register
	}
	return nil
}

func (m *Request) GetUnregister() *UnregisterRequest {
	if m != nil {
		return m.Unregister
	}
	return nil
}

type SetRequest struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SetRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type GetRequest struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type DeleteRequest struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type RegisterRequest struct {
	Id               []byte `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegisterRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type UnregisterRequest struct {
	Id               []byte `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnregisterRequest) Reset()                    { *m = UnregisterRequest{} }
func (m *UnregisterRequest) String() string            { return proto.CompactTextString(m) }
func (*UnregisterRequest) ProtoMessage()               {}
func (*UnregisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UnregisterRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "dht.Request")
	proto.RegisterType((*SetRequest)(nil), "dht.SetRequest")
	proto.RegisterType((*GetRequest)(nil), "dht.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "dht.DeleteRequest")
	proto.RegisterType((*RegisterRequest)(nil), "dht.RegisterRequest")
	proto.RegisterType((*UnregisterRequest)(nil), "dht.UnregisterRequest")
	proto.RegisterEnum("dht.Request_Type", Request_Type_name, Request_Type_value)
}

func init() { proto.RegisterFile("request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x45, 0x69, 0x26, 0x49, 0xeb, 0x6d, 0xd3, 0xa6, 0x83, 0x48, 0x84, 0x4a, 0xcb, 0x2c, 0x24,
	0xb8, 0xc8, 0xa2, 0x9f, 0x20, 0x1d, 0x82, 0x20, 0x2e, 0x92, 0xf4, 0x03, 0x84, 0x3c, 0x6a, 0xb1,
	0xd8, 0x9a, 0x4c, 0x84, 0xfe, 0x8e, 0x5f, 0xea, 0x38, 0x4d, 0x62, 0xaa, 0xee, 0xe6, 0xdd, 0x73,
	0x06, 0xde, 0x7d, 0xf0, 0x0a, 0x7a, 0xaf, 0xa8, 0x54, 0xd1, 0xa1, 0xd8, 0xab, 0x3d, 0x67, 0xf9,
	0x8b, 0x12, 0x9f, 0x16, 0xfa, 0xc9, 0x29, 0xe6, 0x73, 0xd8, 0xea, 0x78, 0xa0, 0xa0, 0xb7, 0xb0,
	0xc2, 0xf1, 0x72, 0x1a, 0x69, 0x1e, 0xd5, 0x2c, 0xca, 0x34, 0xe0, 0x33, 0xb0, 0x92, 0x54, 0x60,
	0x2d, 0x7a, 0xe1, 0x70, 0x39, 0x31, 0x3c, 0x25, 0xd5, 0x7c, 0xd7, 0x74, 0xa3, 0x29, 0xeb, 0xd0,
	0xf8, 0x87, 0x0a, 0xb8, 0x39, 0xed, 0x48, 0x51, 0x60, 0x1b, 0x81, 0x1b, 0x61, 0x65, 0xa2, 0xc6,
	0xb9, 0xc5, 0xa0, 0xa0, 0xcd, 0xb6, 0x54, 0x54, 0x04, 0x8e, 0xb1, 0x2e, 0xeb, 0x25, 0x4e, 0x61,
	0xe3, 0xdd, 0x01, 0xd5, 0x5b, 0x6b, 0xba, 0xc6, 0xbc, 0x32, 0xe6, 0xba, 0x8d, 0x6b, 0x57, 0xdc,
	0xc3, 0x36, 0xbb, 0xf7, 0xc1, 0x52, 0x99, 0xf9, 0xbd, 0xef, 0x47, 0xac, 0x1f, 0x16, 0x07, 0xdc,
	0x95, 0x7c, 0x94, 0x99, 0xf4, 0x19, 0x1f, 0x61, 0x90, 0xc8, 0xf8, 0x21, 0xcd, 0x64, 0xe2, 0xdb,
	0x7c, 0x0c, 0xac, 0x9f, 0xda, 0xd9, 0x11, 0x21, 0xd0, 0xe9, 0x39, 0x04, 0x7b, 0xa5, 0xa3, 0xb9,
	0xd2, 0x05, 0xf7, 0xe0, 0x7c, 0x3c, 0xef, 0x2a, 0xd2, 0x47, 0xd1, 0xa3, 0xb8, 0x06, 0xe2, 0xff,
	0x4d, 0x31, 0x83, 0x77, 0xde, 0xf6, 0x8c, 0xde, 0x60, 0xf2, 0xbb, 0x25, 0x60, 0x6d, 0x73, 0x83,
	0x47, 0x62, 0x8e, 0xe9, 0x9f, 0x6a, 0x5d, 0xe1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x90, 0x7e, 0x13,
	0x58, 0xdc, 0x01, 0x00, 0x00,
}
